#!/usr/bin/env python

import argparse
import logging

from lib.daemon import Daemon
from lib.client import Client


def args_parse():
    parser = argparse.ArgumentParser(description='Managing pomidorkas using pomodoro technique.')

    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--daemon', '-D', action='store_true', default=False,
        help='Run program in daemon mode.')
    mode.add_argument('--client', '-c', action='store_true', default=True,
        help='Run client mode commands.')

    parser.add_argument('action', type=str, nargs='?',
        help='Action to perform: start, stop, status. Defaults to start.')

    parser.add_argument('--data', '-d', type=str,
        default='/tmp/pomidorka.dat',
        help='Path to data file, should be same for daemon and client.')

    parser.add_argument('--pidfile', '-p', type=str,
        default='/tmp/pomidorka.pid',
        help='Path to pidfile, used in daemon mode.')

    parser.add_argument('--logs', '-l', type=str,
        default='/tmp/pomidorka.log',
        help='Path to logs file, used in daemon mode.')

    return parser.parse_args()

if __name__ == "__main__":
    args = args_parse()

    logging.basicConfig(filename=args.logs, level=logging.INFO)
    console = logging.StreamHandler()
    console.setLevel(logging.INFO)
    logging.getLogger('').addHandler(console)
    logger = logging.getLogger(__name__)

    if args.daemon:
        logger.info('Starting daemon mode')
        app = Daemon(logger, args.pidfile, args.data)
        app.run()
    else:
        app = Client(logger, args.pidfile, args.data)

        if args.action == 'start':
            app.start()
        elif args.action == 'stop':
            app.stop()
        else:
            app.status()
