#!/usr/bin/env python

import argparse

from lib.daemon import Daemon
from lib.client import Client


def args_parse():
    parser = argparse.ArgumentParser(description='Managing pomidorkas using pomodoro technique.')

    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--daemon', '-D', action='store_true', default=False,
        help='Run program in daemon mode.')
    mode.add_argument('--client', '-c', action='store_true', default=True,
        help='Run client mode commands.')

    parser.add_argument('action', type=str, nargs='?',
        help='Action to perform: start, stop, status. Defaults to start.')

    parser.add_argument('--data', '-d', type=str,
        default='/tmp/pomidorka.dat',
        help='Path to data file, should be same for daemon and client.')

    parser.add_argument('--pidfile', '-p', type=str,
        default='/tmp/pomidorka.pid',
        help='Path to pidfile, used in daemon mode.')

    return parser.parse_args()

if __name__ == "__main__":
    args = args_parse()

    if args.daemon:
        print('Starting daemon mode')
        app = Daemon(args.pidfile, args.data)
        app.run()
    else:
        app = Client(args.pidfile, args.data)

        if args.action == 'stop':
            app.stop()
        elif args.action == 'status':
            app.status()
        else:
            app.start()
